services:
  alas:
    build:
      context: .
      args:
        JANET_VERSION: 1.32.1
        JPM_VERSION: v1.1.0
    container_name: alas
    image: alas:1.0
    tty: true
    volumes:
      - .:/home/alas
